import { notFound } from "next/navigation";
import { getGenerationById } from "@/lib/supabase";
import type { Metadata } from "next";
import ShareResults from "./ShareResults";

interface PageProps {
  params: Promise<{ id: string }>;
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { id } = await params;
  const { data } = await getGenerationById(id);

  if (!data) {
    return { title: "Not found — Next Video" };
  }

  const title = `Video ideas for ${data.channel_title} — Next Video`;
  const description = `${(data.ideas as unknown[]).length} data-backed video ideas for ${data.channel_title}, generated by Next Video.`;

  return {
    title,
    description,
    openGraph: {
      title,
      description,
      url: `https://nextvideo.youtubeproducer.app/share/${id}`,
      siteName: "YouTube Producer",
      type: "website",
      images: [
        {
          url: "https://nextvideo.youtubeproducer.app/og-image.png",
          width: 1200,
          height: 630,
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: ["https://nextvideo.youtubeproducer.app/og-image.png"],
    },
  };
}

export default async function SharePage({ params }: PageProps) {
  const { id } = await params;
  const { data } = await getGenerationById(id);

  if (!data) {
    notFound();
  }

  return <ShareResults data={data} />;
}
