"use client";

import IdeaCard from "./IdeaCard";
import type { VideoIdea } from "@/lib/ai";

interface IdeaResultsProps {
  ideas: VideoIdea[];
  channelTitle: string;
}

export default function IdeaResults({ ideas, channelTitle }: IdeaResultsProps) {
  if (!ideas.length) return null;

  return (
    <div className="w-full max-w-2xl mx-auto">
      <div className="mb-5">
        <h2 className="text-xl font-semibold text-stone-900 tracking-tight">
          Video ideas for {channelTitle}
        </h2>
        <p className="text-sm text-stone-500 mt-1">
          Based on outlier videos from channels one step ahead of yours
        </p>
      </div>
      <div className="flex flex-col gap-3">
        {ideas.map((idea, i) => (
          <IdeaCard
            key={i}
            index={i}
            title={idea.title}
            insight={idea.insight}
            evidence={idea.evidence}
          />
        ))}
      </div>

      {/* How it works explainer */}
      <div className="mt-8 pt-6 border-t border-stone-200">
        <p className="text-[11px] font-medium text-stone-400 uppercase tracking-wider mb-3">
          How these ideas are generated
        </p>
        <div className="flex flex-col gap-2 text-xs text-stone-500 leading-relaxed">
          <p>
            <span className="font-medium text-stone-600">Peer channels</span> — We find YouTube channels in your niche with slightly more subscribers than yours. These are channels &quot;one step ahead&quot; of you.
          </p>
          <p>
            <span className="font-medium text-stone-600">Outlier videos</span> — For each peer channel, we calculate their median video views. Videos with 3x or more their median are outliers — topics that clearly resonated with their audience.
          </p>
          <p>
            <span className="font-medium text-stone-600">The multiplier (e.g. 5.2x)</span> — Shows how many times more views that video got compared to the channel&apos;s typical video. Higher = stronger signal that the topic works.
          </p>
          <p>
            <span className="font-medium text-stone-600">Idea ranking</span> — Ideas are generated by AI based on the strongest outlier patterns, adapted to your channel&apos;s size and style. Each idea cites evidence from different channels to show the trend isn&apos;t a one-off.
          </p>
        </div>
      </div>
    </div>
  );
}
